# Generated by Django 3.1.8 on 2022-01-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('birthday_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Female', 'Женский'), ('Male', 'Мужской')], default='Male', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала лечения')),
                ('end_date', models.DateField(null=True, verbose_name='Окончание лечения')),
                ('result', models.CharField(choices=[('Helped', 'Помогло'), ('Useless', 'Не помогло')], default=None, max_length=11, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.patient', verbose_name='Пациент')),
            ],
        ),
        migrations.CreateModel(
            name='MedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата документа')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.patient', verbose_name='Пациент')),
                ('treatment_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedApp.treatmentcase', verbose_name='Случай лечения')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(verbose_name='Содержание документа')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MedApp.meddocument', verbose_name='Документ')),
            ],
        ),
    ]
